# Generated by Django 5.0.4 on 2024-05-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn10', models.CharField(max_length=10)),
                ('isbn13', models.CharField(max_length=13)),
                ('overview1', models.TextField()),
                ('overview2', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
