# Generated by Django 5.0.4 on 2024-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_bookdetails_isbn10_alter_bookdetails_isbn13'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='authorImage_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
