# Generated by Django 5.0.4 on 2024-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bookdetails_authorimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='availability',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
