# Generated by Django 5.0.4 on 2024-05-13 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookdetails_availability_bookdetails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
