# Generated by Django 5.0.4 on 2024-05-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bookdetails_created_at_alter_bookdetails_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='created_at',
        ),
    ]
