# Generated by Django 5.0.4 on 2024-05-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_bookdetails_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='availability',
        ),
    ]
