# Generated by Django 5.0.4 on 2024-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_bookdetails_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='btn',
            field=models.CharField(default='Borrow', max_length=100),
        ),
    ]
