# Generated by Django 5.0.4 on 2024-05-19 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bookdetails_available_bookdetails_btn_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.register3'),
        ),
        migrations.AlterField(
            model_name='register3',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
