# Generated by Django 5.0.4 on 2024-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_borrowedbook_user_alter_register3_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register3',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
