# Generated by Django 5.0.4 on 2024-05-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_register3_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='available',
        ),
        migrations.RemoveField(
            model_name='bookdetails',
            name='btn',
        ),
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
