# Generated by Django 5.0.4 on 2024-05-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_bookdetails_available_remove_bookdetails_btn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='btn',
            field=models.CharField(default='Borrow', max_length=100),
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bookdetails')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.register3')),
            ],
        ),
    ]
