# Generated by Django 5.0.4 on 2024-06-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_bookdetails_available_bookdetails_btn_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='authorImage_url',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='image_url',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
